# Generated by Django 4.0.6 on 2022-07-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lesson_title'),
        ('profiles', '0002_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderCourse',
        ),
    ]
