# Generated by Django 4.0.6 on 2022-07-27 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orderitem_ordercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercourse',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordercourse',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
