# Generated by Django 4.0.6 on 2022-08-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('profiles', '0002_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordercourse',
            unique_together={('course', 'user')},
        ),
    ]
