# Generated by Django 4.0.6 on 2022-07-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('course', '0004_course_published_status_alter_course_pay'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='course.course'),
        ),
        migrations.AlterField(
            model_name='ordercourse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.profile'),
        ),
    ]
