# Generated by Django 4.0.6 on 2022-07-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_published_status_alter_course_pay'),
        ('profiles', '0002_initial'),
        ('orders', '0003_alter_ordercourse_course_alter_ordercourse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercourse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
