# Generated by Django 4.0.6 on 2022-07-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('orders', '0004_alter_ordercourse_course_alter_ordercourse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercourse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.profile'),
        ),
    ]
