version: "3.8"
services:

  backend:
    build: .
    container_name: adesua_container
    image: adesua_django
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django
    ports:
      - 8000:8000

    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0/
      - CELERY_BACKEND=redis://redis:6379/0/
    depends_on:
      - database
      - pgadmin
      - esearch
      - redis

  database:
    container_name: postgres_database
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # volumes:
    #   - ./data/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  esearch:
    container_name: search
    image: elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    
  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - '6379:6379'

  celery:
    container_name: celery
    restart: always
    build: .
    volumes:
      - .:/django
    command: celery -A adesua worker -l info
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis

  celery-beat:
    container_name: celery_beat
    restart: always
    build: .
    volumes:
      - .:/django
    command: celery -A adesua beat -l info
    depends_on:
      - celery
      - redis

  flower:
    container_name: flower_adesua
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - "8888:8888"
