version: "3"

services:
  backend:
    build:
      context: ./backend
    command: gunicorn adesua.wsgi --bind 0.0.0.0:8000
    volumes:
      - django_build:/backend
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    ports:
      - 80:8000
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - django_build:/var/www/backend
    depends_on:
      - backend
volumes:
  django_build:
