# Generated by Django 4.0.6 on 2022-07-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_price_alter_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Course Title'),
        ),
    ]
