# Generated by Django 4.0.6 on 2022-07-25 06:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=1, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
