# Generated by Django 4.0.6 on 2022-08-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Lesson Title'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'title')},
        ),
    ]
