# Generated by Django 4.0.6 on 2022-07-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Lesson Title'),
        ),
    ]
