# Generated by Django 4.0.6 on 2022-07-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_status',
            field=models.BooleanField(default=False, verbose_name='Published Status'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pay',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=4, verbose_name='Paid / Free'),
        ),
    ]
