# Generated by Django 4.0.6 on 2022-07-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_category_course_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
