# Generated by Django 4.0.6 on 2022-08-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
