# Generated by Django 4.0.6 on 2022-08-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='value',
            field=models.CharField(max_length=2, unique=True, verbose_name='School Year'),
        ),
    ]
