# Generated by Django 4.0.6 on 2022-07-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(related_name='instructor', to='course.category', verbose_name='Course Categories'),
        ),
    ]
