# Generated by Django 4.0.6 on 2022-08-25 12:06

import apps.course.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('course', '0004_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.courseinstructor', validators=[apps.course.validators.validate_user_type], verbose_name='Course Instructor'),
        ),
    ]
