# Generated by Django 4.0.6 on 2022-08-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('course', '0005_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='profiles.profile', verbose_name='Course Instructor'),
        ),
    ]
