# Generated by Django 4.0.6 on 2022-07-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='instructor', to='course.category', verbose_name='Course Categories'),
        ),
    ]
