# Generated by Django 4.0.6 on 2022-08-11 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_courseinstructor_reviewer_student_user_type'),
        ('course', '0006_alter_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='users.courseinstructor', verbose_name='Course Instructor'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(default=1, upload_to='lesson_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Lesson Video'),
            preserve_default=False,
        ),
    ]
