# Generated by Django 4.0.6 on 2022-08-12 15:45

import apps.course.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_courseinstructor_reviewer_student_user_type'),
        ('course', '0007_alter_course_instructor_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='users.courseinstructor', validators=[apps.course.validators.validate_user_type], verbose_name='Course Instructor'),
            preserve_default=False,
        ),
    ]
