# Generated by Django 4.0.6 on 2022-08-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_courseinstructor_reviewer_student_user_type'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_enrolled', to='users.student'),
        ),
    ]
