# Generated by Django 4.0.6 on 2022-08-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='course_on_free_trail',
            field=models.BooleanField(default=False),
        ),
    ]
