# Generated by Django 4.0.6 on 2022-08-12 14:27

import apps.students.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_alter_courseenrollment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_enrolled', to=settings.AUTH_USER_MODEL, validators=[apps.students.models.validate_user_type]),
            preserve_default=False,
        ),
    ]
