# Generated by Django 4.0.6 on 2022-08-02 20:57

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Accra', max_length=180, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='GH', max_length=2, verbose_name='Country'),
        ),
    ]
