# Generated by Django 4.0.6 on 2022-08-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_city_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='Ghana', max_length=100, verbose_name='Country'),
        ),
    ]
