# Generated by Django 4.0.6 on 2022-08-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_initial'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesonpromotion',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CoursesOnPromotion', to='course.course'),
        ),
    ]
