# Generated by Django 4.0.6 on 2022-09-03 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('promotion', '0001_initial'),
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpromotion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='users.student'),
        ),
        migrations.AddField(
            model_name='trialcourse',
            name='courses_on_trail',
            field=models.ManyToManyField(related_name='courses_on_trail', through='promotion.CoursesOnTrial', to='course.course'),
        ),
        migrations.AddField(
            model_name='trialcourse',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_on_trail', to='users.courseinstructor'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupon', to='promotion.coupon'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='courses_on_promotion',
            field=models.ManyToManyField(related_name='courses_on_promotion', through='promotion.CoursesOnPromotion', to='course.course'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotype', to='promotion.promotype'),
        ),
        migrations.AddField(
            model_name='coursesontrial',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trail', to='course.course'),
        ),
        migrations.AddField(
            model_name='coursesontrial',
            name='trail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_trail', to='promotion.trialcourse'),
        ),
        migrations.AddField(
            model_name='coursesonpromotion',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CoursesOnPromotion', to='course.course'),
        ),
        migrations.AddField(
            model_name='coursesonpromotion',
            name='promotion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='promotion.promotion'),
        ),
        migrations.AlterUniqueTogether(
            name='coursesontrial',
            unique_together={('course_id', 'trail_id')},
        ),
        migrations.AlterUniqueTogether(
            name='coursesonpromotion',
            unique_together={('course_id', 'promotion_id')},
        ),
    ]
