# Generated by Django 4.0.6 on 2022-08-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailcourse',
            name='is_scheduled',
            field=models.BooleanField(default=True),
        ),
    ]
