# Generated by Django 4.0.6 on 2022-08-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='is_schedule',
            field=models.BooleanField(default=True),
        ),
    ]
