# Generated by Django 4.0.6 on 2022-08-16 19:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_promotion_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='promo_reduction',
        ),
        migrations.AddField(
            model_name='promotion',
            name='promo_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promo_percentage',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='percentage reduction for promotion %'),
        ),
    ]
