# Generated by Django 4.0.6 on 2022-08-16 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_remove_promotion_promo_reduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promo_percentage',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='percentage reduction for promotion %'),
        ),
    ]
