def iso_list():
    return [
        "DZ",
        "AO",
        "BJ",
        "BW" "BF" "BI" "CM" "CV",
        "CF" "TD",
        "COM",
        "CG",
        "CD",
        "CI",
        "DJ",
        "EG",
        "GQ",
        "ER",
        "ET",
        "GA",
        "GM",
        "GH",
        "GN" "GW",
        "KE",
        "LS",
        "LR",
        "LY",
        "MG",
        "ML" "MW",
        "MR",
        "MU",
        "YT" "MA",
        "MZ",
        "NA",
        "NE",
        "NG",
        "RE",
        "RW",
        "ST",
        "SN",
        "SC",
        "SL",
        "SO",
        "ZA",
        "SS",
        "SD",
        "SZ",
        "TZ",
        "TG",
        "TN",
        "UG",
        "EH",
        "ZM",
        "ZW",
    ]
