# Generated by Django 4.0.6 on 2022-08-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_instructor'),
        ('users', '0003_courseinstructor_reviewer_student_user_type'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_ratings', to='course.course', verbose_name='Course being rated'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_ratings', to='users.student', verbose_name='Enrolled Student providing the rating'),
        ),
    ]
