# Generated by Django 4.0.6 on 2022-08-17 17:37

import apps.ratings.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_ratings', to='users.student', validators=[apps.ratings.validators.validate_user_type], verbose_name='Enrolled Student providing the rating'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('rater', 'course')},
        ),
    ]
