# Generated by Django 4.0.6 on 2022-07-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('ratings', '0002_alter_rating_unique_together_alter_rating_rater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile', verbose_name='Enrolled Student providing the rating'),
        ),
    ]
