# Generated by Django 4.0.6 on 2022-08-14 19:59

import apps.ratings.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_ratings', to=settings.AUTH_USER_MODEL, validators=[apps.ratings.validators.validate_user_type], verbose_name='Enrolled Student providing the rating'),
        ),
    ]
