# Generated by Django 4.0.6 on 2022-08-12 15:45

import apps.ratings.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_courseinstructor_reviewer_student_user_type'),
        ('ratings', '0003_alter_rating_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_ratings', to='users.student', validators=[apps.ratings.validators.validate_user_type], verbose_name='Enrolled Student providing the rating'),
        ),
    ]
